agent:vector:
  - 'docs/Plan.md'
  - '.notes/features/**'

agent:pixel:
  - 'tests/**'
  - '**/__tests__/**'
  - 'apps/**/tests/**'
  - 'packages/**/tests/**'
  - 'playwright.config.*'
  - 'jest.config.*'
  - 'vitest.config.*'
  - 'cypress.config.*'

agent:forge:
  - 'api/**'
  - 'server/**'
  - 'db/**'
  - 'migrations/**'
  - 'services/**'
  - 'src/server/**'
  - 'src/api/**'
  - 'src/services/**'
  - 'apps/**/api/**'
  - 'apps/**/server/**'
  - 'apps/**/services/**'
  - 'apps/**/src/server/**'
  - 'apps/**/src/api/**'
  - 'apps/**/server/src/**'
  - 'apps/**/api/src/**'
  - 'packages/**/server/**'
  - 'packages/**/api/**'
  - 'packages/**/services/**'
  - 'packages/**/server/src/**'
  - 'packages/**/api/src/**'

agent:link:
  - 'app/**'
  - 'pages/**'
  - 'components/**'
  - 'styles/**'
  - 'web/**'
  - 'frontend/**'
  - 'src/**'
  - 'apps/**/app/**'
  - 'apps/**/pages/**'
  - 'apps/**/components/**'
  - 'apps/**/styles/**'
  - 'packages/ui/**'
  - 'packages/web/src/**'
  - 'packages/**/ui/**'
  - 'packages/**/components/**'
  - 'packages/**/src/components/**'

agent:glide:
  - 'app/mobile/**'
  - 'pwa/**'
  - 'public/**'
  - 'src/pwa/**'
  - 'src/public/**'
  - 'service-worker.js'
  - 'service-worker.ts'
  - 'sw.js'
  - 'sw.ts'
  - 'apps/**/pwa/**'
  - 'apps/**/src/pwa/**'
  - 'apps/**/public/**'
  - 'packages/**/pwa/**'
  - 'packages/**/public/**'

agent:apex:
  - 'android/**'

agent:cider:
  - 'ios/**'

agent:muse:
  - 'docs/**'
  - 'README.md'
  - 'CHANGELOG.md'
  - 'apps/docs/**'
  - 'apps/**/docs/**'
  - 'packages/docs/**'
  - 'packages/**/docs/**'

agent:nexus:
  - '.github/**'
  - '.ci/**'
  - 'Dockerfile*'
  - 'deploy/**'
  - 'env.example'
  - 'docs/github/**'

agent:scout:
  - 'docs/research.md'
  - 'docs/research/**'

agent:sentinel:
  - 'docs/security/**'
  - 'security/**'
